services:
  app-node:
    image: ghcr.io/abelmv29/app-challenge:latest
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: challege_api
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      PORT: 3000
      TOKEN_EXPIRY_HOURS: 24
    secrets:
      - db_user
      - db_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        #limite de consumo
        limits:
          cpus: '0.40'
          memory: 512M
        #reserva minima garantizada
        reservations:
          cpus: '0.20'
          memory: 256M

  postgres:
    image: postgres:17.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: challege_api
    secrets:
      - db_user
      - db_password
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 800M
        reservations:
          cpus: '0.15'
          memory: 400M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 180s
volumes:
  postgres_data:

networks:
  net:
    driver: overlay

secrets:
  db_user:
    external: true
  db_password:
    external: true