version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d' # retention policy de 30 días
    networks:
      - app_challenge_net
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - app_challenge_net
    ports:
      - 3000:3000

volumes:
  grafana-storage:
  prometheus-storage:

networks:
  app_challenge_net:
    external: true