version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d' # retention policy de 30 días
    networks:
      - app_challenge_net
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    volumes:
      - ./alert_manager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - app_challenge_net
    ports:
      - 9093:9093
    secrets:
      - slack_webhook

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - app_challenge_net
    # Nuestra api de express se ejecuta en el puerto 3000
    # y Grafana por defecto también usa el puerto 3000,
    # por lo que cambiamos el puerto de Grafana a 3001
    ports:
      - 3001:3000
secrets:
  slack_webhook:
    external: true

volumes:
  grafana-storage:
  prometheus-storage:

networks:
  app_challenge_net:
    external: true