name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_ACTOR }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/abelmv29/app-challenge:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
