name: build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_ACTOR }}
          password: ${{ secrets.GH_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--debug"
          
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/abelmv29/app-challenge:${{ github.event.release.tag_name }}
            ghcr.io/abelmv29/app-challenge:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  dispatch:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:

      - name: Trigger deploy workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: ${{ github.repository }}
          workflow: 'deploy.yml'
          token: ${{ secrets.GH_TOKEN }}
          ref: main
          inputs: |
            tag_name: "${{ github.event.release.tag_name }}"
