name: deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name of the release to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Connect to server and pull image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          # previo: loguearse en github container registry, ya que el pull de la imagen requiere autenticación
          script: |
            echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ secrets.GH_ACTOR }} --password-stdin
            docker pull ghcr.io/abelmv29/app-challenge:${{ github.event.inputs.tag_name }}

      - name: Deploy with rolling update
        id: deploy_step
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            set -e
            echo "Comprobando Swarm..."
            if ! docker info | grep -q 'Swarm: active'; then
              echo "Iniciando Docker Swarm..."
              docker swarm init
            fi
            echo "Creando secrets de Docker si no existen..."
            if ! docker secret ls --format '{{.Name}}' | grep -q '^db_user$'; then
              echo "${{ secrets.DB_USER }}" | docker secret create db_user -
            fi
            if ! docker secret ls --format '{{.Name}}' | grep -q '^db_password$'; then
              echo "${{ secrets.DB_PASSWORD }}" | docker secret create db_password -
            fi
            echo "Comprobando si el servicio existe..."
            if ! docker service ls --filter name=app_challenge_app --format '{{.Name}}' | grep -q 'app_challenge_app'; then
              echo "Servicio no existe, deploy inicial..."
              docker stack deploy -c ~/production/docker-compose.prod.yml app_challenge
            else
              echo "Servicio existe, realizando rolling update..."
              docker service update \
                --image ghcr.io/abelmv29/app-challenge:${{ github.event.inputs.tag_name }} \
                --update-parallelism 1 \
                --update-delay 10s \
                app_challenge_app-node
              fi

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Deployment completed successfully! Release: ${{ github.event.inputs.tag_name }} - Commit: ${{ github.sha }}'

      - name: Slack Notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook_type: incoming-webhook
          payload: |
            {
              "text": "Deployment *${{ job.status }}* 🚀\nRelease: ${{ github.event.inputs.tag_name }}\nCommit: ${{ github.sha }}"
            }
